name: Deploy Client to Vercel
on:
    push:
        branches:
            - master
            - main
    release:
        types:
            - created
    workflow_dispatch:
jobs:
    vercel:
        runs-on: ubuntu-latest
        name: Deploy Client to Vercel
        steps:
         - uses: actions/checkout@v2
           name: Checkout
         - uses: actions/setup-node@v1
           name: Setup Node
           with:
                node-version: 18.x
         - name: CD into client
           run: cd apps/client
         - name: Install Dependencies
           run: npm install
         - name: Test Env
           run: echo ${{ secrets.VERCEL_TOKEN }} && echo ${{ secrets.VERCEL_ORG_ID }} && echo ${{ secrets.VERCEL_PROJECT_ID }}
         - name: Deploy to Vercel
           run: |
              prodRun=""
                if [ "${{ github.event_name }}" == "release" ]; then
                    prodRun="--prod"
                fi
              npx vercel --token ${{ secrets.VERCEL_TOKEN }} $prodRun
            
        env:
                VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
